version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run: 
          name: Restore packages
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: Build website
          command: npm run build
      - run: 
          name: Archive website
          command: npm run archive
      - persist_to_workspace:
          root: ./dist
          paths:
            - release.zip
  publish:
    docker:
      - image: cibuilds/github      
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ./dist
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=v0.0.1
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./dist/release.zip

workflows:
  version: 2
  release:
    jobs:
      - build
      - publish:
          requires:
           - build